#!name=12306去广告
#!desc=过滤12306应用内广告及开屏广告
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/12306.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Rule]
DOMAIN,ad.12306.cn,DIRECT

[Script]
移除12306开屏广告 = type=http-request, pattern=^https:\/\/ad\.12306\.cn\/ad\/ser\/getAdList$, script-path=https://kelee.one/Resource/JavaScript/12306/12306_remove_splashscreen_ads.js, requires-body=true

移除12306应用内广告 = type=http-request, pattern=^https:\/\/mobile\.12306\.cn\/otsmobile\/app\/mgs\/mgw\.htm$, script-path=https://kelee.one/Resource/JavaScript/12306/12306_remove_ads.js

[MITM]
hostname = %APPEND% ad.12306.cn, mobile.12306.cn

