#!name=360摄像机去广告
#!desc=移除开屏广告、首页推广、底栏商城入口及我的页面推广。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/360SmartCamera.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Rule]
DOMAIN,ad.jia.360.cn,REJECT
DOMAIN,ad.iot.360.cn,REJECT

[Body Rewrite]
http-response-jq ^https:\/\/jia\.360\.cn\/conf\/v1\.json 'delpaths([["tab_conf"]])'
http-response-jq ^https:\/\/jia\.360\.cn\/conf\/v1\.json 'delpaths([["ad_conf"]])'
http-response-jq ^https:\/\/jia\.360\.cn\/conf\/v1\.json 'delpaths([["activity"]])'

[MITM]
hostname = %APPEND% jia.360.cn

