#!name=555电影去广告
#!desc=移除开屏广告和各类横幅广告，支持iPadOS。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/555DY.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Body Rewrite]
http-response-jq ^https:\/\/(app-v1\.ecoliving168\.com|852b95d36\.xwlpk\.cn)\/api\/v1\/movie\/index_recommend\? '.data[].list |= map(select(.type != 3)) | .data |= map(select(.layout != "advert_self"))'

[MITM]
hostname = %APPEND% app-v1.ecoliving168.com, 852b95d36.xwlpk.cn

