#!name=ECOVACS HOME去广告
#!desc=移除横幅推广，精简底栏。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/EcovacsHome.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/api-app\.dc-cn\.cn\.ecouser\.net\/api\/ecms\/app\/ad\/ - reject-dict
^https:\/\/gl-cn-api\.ecovacs\.cn\/v1\/private\/ - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/gl-cn-api\.ecovacs\.cn\/v3\/private\/ '.data.navigateInfoResponseList |= map(select(.positionType == "Robot" or .positionType == "Mine"))'

[MITM]
hostname = %APPEND% gl-cn-api.ecovacs.cn, api-app.dc-cn.cn.ecouser.net

