#!name=Fileball网盘挂载
#!desc=支持挂载阿里云盘、夸克网盘和PikPak网盘，点击下方署名查看使用方法。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/Fileball.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Script]
三合一网盘挂载 = type=http-request, pattern=^http:\/\/(aliyun|quark|pikpak)\.example\.com, script-path=https://kelee.one/Resource/JavaScript/Fileball/Fileball_mount.js, requires-body=true

[MITM]
hostname = %APPEND% aliyun.example.com, quark.example.com, pikpak.example.com

