#!name=IT之家去广告
#!desc=过滤IT之家信息流广告和文末广告，自定义移除置顶和轮播图，自定义移除项需在插件配置。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/IThome.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https?:\/\/dat\.ruanmei\.com\/ithome\/money\/acd\.json$ - reject

[Script]
IT之家去广告 = type=http-response, pattern=^https:\/\/napi\.ithome\.com\/api\/(news\/indexv2\/iphone\/\d+$|topmenu\/getfeeds\?), script-path=https://kelee.one/Resource/JavaScript/IThome/IThome_remove_ads.js, requires-body=true, argument="[{{{removeAllBanners}}},{{{removePinnedArticles}}}]"

[MITM]
hostname = %APPEND% napi.ithome.com, api.zuihuimai.com, dat.ruanmei.com

