#!name=Jump去广告
#!desc=移除Jump开屏广告
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/Jump.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Rule]
DOMAIN,zlsdk.1rtb.net,REJECT
DOMAIN,jp.ad.gameley.com,REJECT
DOMAIN,toblog.ctobsnssdk.com,REJECT
DOMAIN,s3plus.meituan.net,REJECT
DOMAIN,images.pinduoduo.com,REJECT
DOMAIN,qh-material.taobao.com,REJECT
DOMAIN-SUFFIX,admobile.top,REJECT

[Body Rewrite]
http-response-jq ^https:?\/\/switch.jumpvg.com\/jump\/getlaunchad\/v2$ 'del(.data.adList)|.data.launchAd.showType=0'
http-response-jq ^https:?\/\/switch.jumpvg.com\/jump\/recommend\/ad_conf$ '.data=[]'

[MITM]
hostname = %APPEND% switch.jumpvg.com

