#!name=Pinterest去广告
#!desc=移除瀑布流、更多探索内容中的广告
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/Pinterest.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Body Rewrite]
http-response-jq ^https:\/\/api\.pinterest\.com\/v\d\/feeds\/home\/\? '.data |= map(select(.is_promoted == false or .is_promoted == "false"))'
http-response-jq ^https:\/\/api\.pinterest\.com\/v\d\/pins\/\d+\/related\/modules\/\? '.data |= map(select(.is_promoted == false or .is_promoted == "false"))'

[MITM]
hostname = %APPEND% api.pinterest.com

