#!name=QQ音乐去广告
#!desc=过滤QQ音乐广告
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/QQMusic.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Rule]
DOMAIN,adstats.tencentmusic.com,REJECT
DOMAIN,ad.tencentmusic.com,REJECT
DOMAIN,adcdn.tencentmusic.com,REJECT
DOMAIN,adcdn6.tencentmusic.com,REJECT
DOMAIN,adexpo.tencentmusic.com,REJECT
DOMAIN,adclick.tencentmusic.com,REJECT
DOMAIN,mc.tencentmusic.com,REJECT
DOMAIN,monitor.music.qq.com,REJECT
DOMAIN,tmead.y.qq.com,REJECT
DOMAIN,tmeadbak.y.qq.com,REJECT
DOMAIN,tmeadquic.y.qq.com,REJECT

