#!name=TubeMax去广告
#!desc=过滤TubeMax广告
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/TubeMax.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Rule]
DOMAIN,app.tubemaxapp.com,PROXY
DOMAIN-SUFFIX,adjust.com,REJECT
DOMAIN-SUFFIX,applvn.com,REJECT
DOMAIN-SUFFIX,app-measurement.com,REJECT
DOMAIN-SUFFIX,pangle.io,REJECT
DOMAIN-SUFFIX,applovin.com,REJECT
DOMAIN-SUFFIX,appier.net,REJECT
DOMAIN-SUFFIX,adsmoloco.com,REJECT
DOMAIN-SUFFIX,adcanvas.com,REJECT

[URL Rewrite]
^https:\/\/.*\.i18n-pglstatp\.com\/obj\/ad-pattern-sg - reject

[MITM]
hostname = %APPEND% *.i18n-pglstatp.com

