#!name=YouTube 去广告
#!desc=YouTube 去广告
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Script]
yt-sub-clean = type=http-request, pattern=^https://www\.youtube\.com/api/timedtext\?.*_ytzhsub=1, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/refs/heads/main/yt-sub-clean.js, timeout=60

yt-zh-sub = type=http-response, pattern=^https://www\.youtube\.com/api/timedtext\?, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/refs/heads/main/yt-zh-sub.js, requires-body=true, max-size=-1, timeout=60

[MITM]
hostname = %APPEND% www.youtube.com

