#!name=YY语音去广告
#!desc=移除开屏广告、应用内弹窗、任务推广、频道横幅推广，精简广场顶部标签。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/YYVoiceTool.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/yuyin-api\.baizhanlive\.com\/homepage\/flashscreen\/get\? - reject-dict
^https:\/\/yuyin-api\.baizhanlive\.com\/homepage\/homepage\/banner\? - reject-dict
^https:\/\/web\.yy\.com\/yyvoice_task_sys\/bar\.html\? - reject
^https:\/\/yuyin-api\.baizhanlive\.com\/search\/search\/hotword\? - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/yuyin-api\.baizhanlive\.com\/postsquare\/college\/page\/tabsV3\? '.data.tabList |= map(select(.code == "post" or .code == "teamup" or .code == "college" or .code == "aiSecretRoom"))'

[MITM]
hostname = %APPEND% yuyin-api.baizhanlive.com, web.yy.com

