#!name=ZAKER去广告
#!desc=移除开屏广告、置顶轮播图广告和文末广告。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/ZAKER.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/iphone\.myzaker\.com\/zaker\/cover\.php\? - reject-dict
^https:\/\/iphone\.myzaker\.com\/zaker\/block_top_ad\.php\? - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/iphone\.myzaker\.com\/zaker\/article_mongo_sec\.php\? 'delpaths([["data","ad_url"]])'
http-response-jq ^https:\/\/ggs\.myzaker\.com\/zk_article_ad\.php\? 'delpaths([["data","article_bottom"]])'
http-response-jq ^https:\/\/ggs\.myzaker\.com\/zk_article_ad\.php\? 'delpaths([["data","recommend_ad"]])'
http-response-jq ^https:\/\/iphone\.myzaker\.com\/zaker\/follow_promote\.php\? '.data.list |= map(select(.type != "web"))'
http-response-jq ^https:\/\/iphone\.myzaker\.com\/zaker\/car_tab\/index\.php\? '.data.gallery |= map(select(.type != "web"))'

[MITM]
hostname = %APPEND% iphone.myzaker.com, ggs.myzaker.com

