#!name=一甜相机去广告
#!desc=移除开屏广告、悬浮广告及图片选择器横幅广告。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/Yitian.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/(m2u-api\.getkwai|api-m2u\.kuaishou)\.com\/api-server\/api\/v1\/ad\/ - reject-dict
^https:\/\/(m2u-api\.getkwai|api-m2u\.kuaishou)\.com\/api-server\/api\/v4\/op\/actPositions\? - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/(m2u-api\.getkwai|api-m2u\.kuaishou)\.com\/api-server\/api\/v1\/system\/configs\? 'delpaths([["data","shouldUseLMAdFirst"]])'
http-response-jq ^https:\/\/(m2u-api\.getkwai|api-m2u\.kuaishou)\.com\/api-server\/api\/v1\/system\/configs\? 'delpaths([["data","incentiveCfgList"]])'

[MITM]
hostname = %APPEND% m2u-api.getkwai.com, api-m2u.kuaishou.com

