#!name=两步路户外助手去广告
#!desc=移除开屏广告、弹窗广告，精简我的页面。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/2bulu.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/helper\.2bulu\.com\/search\/searchHotKeyList\? - reject-dict
^https:\/\/helper\.2bulu\.com\/promote\/getAppUserModule\? - reject-dict
^https:\/\/helper\.2bulu\.com\/proSpecial\/allData\? - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/helper\.2bulu\.com\/getAppEntranceConfig\? '.configData=(.configData|fromjson|del(.adPlatform,.adIntertitialShowType,.adsConfig,.adIntertitialDisplayedLimit,.adSplashShowTypeWhenHotStart,.adIntertitialDayDisplayedMaxCount,.od_adsType,.showMeBaiHeAdView)|tojson)'

[MITM]
hostname = %APPEND% helper.2bulu.com

