#!name=丰巢去广告
#!desc=移除弹窗，精简首页和生活服务。此插件需要IPA签名方可使用，App Store用户请勿使用此插件，务必点击下方主页链接查看详细教程。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/FC_Box.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/consumer\.fcbox\.com\/fcboxactivityweb\/api\/v\d\/clientPage\/modulesAggregated\? - reject-dict
^https:\/\/consumer\.fcbox\.com\/fcboxactivityweb\/api\/v\d\/clientPage\/jinGangFirst\? - reject-dict
^https:\/\/consumer\.fcbox\.com\/v2\/home\/mallInfo$ - reject-dict
^https:\/\/dsp\.fcbox\.com\/adSearch\/ - reject-dict
^https:\/\/consumer\.fcbox\.com\/hs-portal\/app\/config\/page\/home\/v2\? - reject-dict
^https:\/\/consumer\.fcbox\.com\/post\/suggestion\/query$ - reject-dict
^https:\/\/consumer\.fcbox\.com\/fcboxactivityweb\/marketingEntrance\/retentionPopup$ - reject-dict
^https:\/\/consumer\.fcbox\.com\/fcboxactivityweb\/api\/clientPopup\/v\d\/queryPopupWithPriority$ - reject-dict
^https:\/\/consumer\.fcbox\.com\/fcboxactivityweb\/api\/guidePopup\/popup$ - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/consumer\.fcbox\.com\/v1\/dynamicConfig\/findTabbarConfig\/mainPage$ 'delpaths([["data","lifeService"]])'
http-response-jq ^https:\/\/consumer\.fcbox\.com\/v1\/dynamicConfig\/findTabbarConfig\/mainPage$ 'delpaths([["data","mall"]])'

[MITM]
hostname = %APPEND% consumer.fcbox.com, dsp.fcbox.com

