#!name=云鲸智能去广告
#!desc=移除开屏广告、横幅推广，禁用商城。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/NarwelRobots.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/cn-app\.narwaltech\.com\/operate\/appPosition\/listSplash\? - reject-dict
^https:\/\/cn-app\.narwaltech\.com\/operate\/cactivity\/listByResourceIds\?resourceIds=(user_center_banner|index_banner) - reject-dict
^https:\/\/store\.narwal\.com\/mall\/customPage\/getByPageKeyword\? - reject-dict

[MITM]
hostname = %APPEND% cn-app.narwaltech.com, store.narwal.com

