#!name=剑网三无界去广告
#!desc=移除热门推送活动，并解决无法在Loon运行时更新和登录的问题。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/SeasunJX3.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[General]
always-real-ip = %APPEND% *-update.xoyocdn.com, xg-flow.xoyo.com

[URL Rewrite]
^https:\/\/jx3comm\.xoyocdn\.com\/jx3gc\/zhcn\/login_ad\/WebCareer\/WebCareerTab\.txt - reject

[MITM]
hostname = %APPEND% jx3comm.xoyocdn.com

