#!name=医考帮去广告
#!desc=移除横幅推广、弹窗、首页悬浮挂件。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/YiKaoBang.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/api\.yikaobang\.com\.cn\/index\.php\/client\/main\/ads\? - reject-dict
^https:\/\/api\.yikaobang\.com\.cn\/index\.php\/client\/Main\/startPage\? - reject-dict

[MITM]
hostname = %APPEND% api.yikaobang.com.cn

