#!name=华尔街见闻去广告
#!desc=移除开屏广告、文末广告、信息流广告，精简底栏。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/FinanceNews.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/advertising\/ - reject-dict
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/kvconfig\/items\/search_keywords_wscnvip$ - reject-dict
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/search\/hotsearch\? - reject-dict
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/content\/articles\/hot\? - reject-dict
^https:\/\/wallstreetcn\.com\/app-faas\/coupon\/user\/search\/popup$ - reject-dict
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/content\/lives\/relateddata\/ - reject-dict
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/content\/articles\/relateddata\/ - reject-dict
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/content\/carousel\/information-flow\? - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/kvconfig\/items\/tabbarconfig1$ '.data.items |= [.[] | select(.key == "news" or .key == "live")]'
http-response-jq ^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/content\/articles\/ 'delpaths([["data","recommend_vip_img_uri"]])'
http-response-jq ^https:\/\/api-one-wscn\.awtmt\.com\/\/apiv1\/kvconfig\/items\/membersrights$ 'delpaths([["data","vip_article"]])'

[MITM]
hostname = %APPEND% api-one-wscn.awtmt.com

