#!name=南网在线去广告
#!desc=移除首页推广，精简搜索页和我的页面。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/CSG.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/95598\.csg\.cn\/mp\/ucs\/ma\/zt\/content\/queryHotInformations$ - reject-dict
^https:\/\/95598\.csg\.cn\/mp\/mpaas\/rubik\/openapi\/rubik\/mobile\/getRubikScene$ - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/95598\.csg\.cn\/mp\/mpaas\/mgw\.htm$ 'if .info | contains("RUBIK-TRACEID:") then .scene.page.areas |= map(select(.areaId | test("kingkong_|9grid_|message_|nearmap_|recommend_"))) else . end'

[MITM]
hostname = %APPEND% 95598.csg.cn

