#!name=哔哩哔哩去广告
#!desc=哔哩哔哩去广告
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/cm\.bilibili\.com\/cm\/api\/(conversion|fees)\/ - reject-dict
^https:\/\/dataflow\.biliapi\.com\/log\/pbmobile\/ - reject-200
^https:\/\/api-pt\.chuangyuejoy\.com\/ad\/ - reject-dict

[Script]
bili_view_ad = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/bilibili\.app\.interface\.v1\.Search\/DefaultWords$, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/refs/heads/main/bili_view_ad.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60

bili_view_ad = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/bilibili\.app\.show\.v1\.Popular\/Index$, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/refs/heads/main/bili_view_ad.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60

bili_view_ad = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/bilibili\.app\.dynamic\.v2\.Dynamic\/DynAll$, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/refs/heads/main/bili_view_ad.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60

[MITM]
hostname = %APPEND% *bili*, api-pt.chuangyuejoy.com

