#!name=图怪兽去广告
#!desc=移除开屏广告、弹窗广告、各页面横幅推广。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/TuGuaiShou.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/api\.818ps\.com\/v4\/advertisement\/ - reject-dict
^https:\/\/api\.818ps\.com\/v4\/popup\/ - reject-dict
^https:\/\/api\.818ps\.com\/v4\/festival\/newYear\/pop\? - reject-dict

[MITM]
hostname = %APPEND% api.818ps.com

