#!name=堆糖去广告
#!desc=移除开屏广告、信息流广告、热搜排行榜广告、我的页面横幅广告，移除关注推荐。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/DuiTang.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/(www|api)\.duitang\.com\/napi\/(ad|ads)\/ - reject-dict
^https:\/\/api\.duitang\.com\/napi\/infra\/settings\/ - reject-dict
^https:\/\/api\.duitang\.com\/napi\/vienna\/daren\/daren\/recommend\/ - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","REWARD_AD_PLACES"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","SPLASH_SWING_OPEN"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","REWARD_AD_PHOTO_EDITOR"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","REWARD_AD_PAG_EDITOR"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","AD_PRICE_SHOW"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","AD_SCREEN_WAKEUP_TIME"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","REWARD_AD_CUTOUT_NUM"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","AD_HOME_ENTER_POP_COUNT"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","SHARE_BANNER"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","AD_MENU_SELECTIONS"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","ME_TAB","ANNOUNCEMENT"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","ME_TAB","MEMBERSHIP"]])'
http-response-jq ^https:\/\/(www|api)\.duitang\.com\/napi\/settings\/ 'delpaths([["data","ME_TAB","MEMBERSHIP2"]])'

[MITM]
hostname = %APPEND% api.duitang.com, www.duitang.com

