#!name=小桔充电去广告
#!desc=移除横幅广告、弹窗广告，精简我的页面。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/XiaojukejiCharge.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/energy\.xiaojukeji\.com\/energy\/hummer\/api\/resource\/display($|\?) - reject-dict
^https:\/\/energy\.xiaojukeji\.com\/lego\/api\/orderSprint\/stair\/info($|\?) - reject-dict
^https:\/\/energy\.xiaojukeji\.com\/station-api\/search\/preWords$ - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/energy\.xiaojukeji\.com\/am\/marketing\/api\/member\/facade\/charge\/personal\/center\? 'delpaths([["data"]])'

[Map Local]
^https:\/\/am\.didistatic\.com\/static\/am\/cf-terminal\/epower\/epower-thanos-app\/\d+\.\d+\.\d+\/pages\/people\/index\.js$ data-type=file data="https://kelee.one/Resource/JavaScript/XiaojukejiCharge/XiaojukejiCharge_remove_ads.js" header="Content-Type:text/plain"

[MITM]
hostname = %APPEND% energy.xiaojukeji.com, am.didistatic.com

