#!name=小蚕霸王餐去广告
#!desc=移除开屏广告、首页横幅推广、红包推广、更新弹窗。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/XiaoCan.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/web2\.realtech-inc\.com\/oss\/xc-app-assets\/configs\/common\/theme\.json - reject-dict
^https:\/\/sdk\.1rtb\.net\/sdk\/req_ad\? - reject-dict
^https:\/\/gw\.xiaocantech\.com\/g\/pa - reject-dict

[Header Rewrite]
http-request ^https:\/\/gw\.xiaocantech\.com\/rpc header-replace-regex 'methodname' '.*(GetBannerList|IsShowOrderAwardPopup|UserLifeShopList|BrandBannerList|GetPromotionGlobalCfg)' 'null'

[MITM]
hostname = %APPEND% gw.xiaocantech.com, web2.realtech-inc.com, sdk.1rtb.net

