#!name=小黑盒去广告
#!desc=移除开屏广告和热点板块信息流广告
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/XiaoHeiHe.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/api\.xiaoheihe\.cn\/account\/get_ads_info_v2 - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/api\.xiaoheihe\.cn\/bbs\/app\/feeds\/news '.result.links |= map(if .content_type == 27 then del(.title, .ad_pm, .img_gif, .idea_id, .ad_report, .label, .source, .intranet_only, .ad_cm, .content_type, .PROTOCOL, .img, .ad_ratio) else . end)'

[MITM]
hostname = %APPEND% api.xiaoheihe.cn

