#!name=得间小说去广告
#!desc=移除开屏广告、章末广告，移除扉页广告提示、听书界面广告提示、搜索栏填充词。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/iReaderDejian.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Rule]
DOMAIN,smad.ms.zhangyue.net,REJECT
DOMAIN,saad.ms.zhangyue.net,REJECT

[URL Rewrite]
^https:\/\/dj\.palmestore\.com\/djad\/ - reject-dict
^https:\/\/dj\.palmestore\.com\/zybk\/api\/ad\/ - reject-dict
^https:\/\/dj\.palmestore\.com\/zyapi\/bookstore\/ad\/ - reject-dict
^https:\/\/dj\.palmestore\.com\/zybk\/api\/bookshelf\/index\? - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/dj\.palmestore\.com\/zybk\/api\/powerup\/userGroup\? 'delpaths([["body","sevenDaysAd"]])'
http-response-jq ^https:\/\/dj\.palmestore\.com\/zybk\/api\/powerup\/userGroup\? 'delpaths([["body","shortPlayShow"]])'
http-response-jq ^https:\/\/dj\.palmestore\.com\/zybk\/api\/powerup\/userGroup\? 'delpaths([["body","sdkShortPlayAB"]])'
http-response-jq ^https:\/\/dj\.palmestore\.com\/zybk\/api\/search\/index\? 'delpaths([["body","keywords"]])'

[MITM]
hostname = %APPEND% dj.palmestore.com

