#!name=微信公众号去广告
#!desc=过滤微信公众号广告
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/Weixin.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Rule]
DOMAIN-SUFFIX,wxs.qq.com,REJECT

[URL Rewrite]
^https:\/\/mp\.weixin\.qq\.com\/mp\/(cps_product_info|getappmsgad|jsmonitor|masonryfeed|relatedarticle)\? - reject-dict
^https:\/\/mp\.weixin\.qq\.com\/mp\/relatedsearchword - reject-dict

[MITM]
hostname = %APPEND% mp.weixin.qq.com

