#!name=挖财记账去广告
#!desc=移除弹窗广告、推广语横幅和右下角悬浮广告。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/WaCaiJiZhang.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/jz\.wacaijizhang\.com\/api\/banners\/ribbon\? - reject-dict
^https:\/\/jz\.wacaijizhang\.com\/api\/banners\/list\? - reject-dict
^https:\/\/jz\.wacaijizhang\.com\/api\/resource\/universal\/fetch$ - reject-dict

[MITM]
hostname = %APPEND% jz.wacaijizhang.com

