#!name=无他相机去广告
#!desc=移除开屏广告、拍摄页面广告、右小角广告，精简底栏。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/WutaCamera.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Body Rewrite]
http-response-jq ^https:\/\/api-release\.wuta-cam\.com\/ad_tree$ 'delpaths([["regular","splash"]])'
http-response-jq ^https:\/\/api-release\.wuta-cam\.com\/ad_tree$ 'delpaths([["big_day"]])'
http-response-jq ^https:\/\/api-release\.wuta-cam\.com\/ad_tree$ 'delpaths([["big_day_overrides"]])'
http-response-jq ^https:\/\/api-release\.wuta-cam\.com\/ad_tree$ 'delpaths([["regular","home_bottom_right_entry_v2"]])'
http-response-jq ^https:\/\/api-release\.wuta-cam\.com\/ad_tree$ 'delpaths([["regular","pic_upload_alert"]])'
http-response-jq ^https:\/\/api-release\.wuta-cam\.com\/ad_tree$ 'delpaths([["regular","retouching_before_icon"]])'
http-response-jq ^https:\/\/api-release\.wuta-cam\.com\/ad_tree$ '.regular.homepage_25_bottom_nav_bar|=map(.button_list|=map(select(.name|IN("home","me"))))'

[MITM]
hostname = %APPEND% api-release.wuta-cam.com

