#!name=最右去广告
#!desc=移除开屏广告、信息流广告和广告轮播图。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/ZuiYou.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Rule]
DOMAIN,adapi.izuiyou.com,REJECT
URL-REGEX,"^http:\/\/mercury-gateway\.ixiaochuan\.cn\/mercury\/v1\/ad\/",REJECT-DICT
URL-REGEX,"^http:\/\/file-share\.izuiyou\.com\/octopus\/media\/templates\/search_home_page_(nv|nv_v2)\/search_home_page_nv",REJECT

[URL Rewrite]
^https?:\/\/api\.izuiyou\.com\/config\/get_banner - reject-dict
^https?:\/\/api\.izuiyou\.com\/ad\/ - reject
^https:\/\/zyfile\.izuiyou\.com\/zyfile\/c2\/a0\/[a-z0-9-]+\.json - reject-dict

[MITM]
hostname = %APPEND% api.izuiyou.com, zyfile.izuiyou.com

