#!name=比特球云盘去广告
#!desc=移除开屏广告和各类横幅推广。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/BitqiuPan.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/pan-api\.bitqiu\.com\/activity\/getPromoteGuide$ - reject-dict
^http:\/\/pan-api\.bitqiu\.com\/activity\/getUrlList$ - reject-dict
^https:\/\/pan-api\.bitqiu\.com\/activity\/guides$ - reject-dict

[MITM]
hostname = %APPEND% pan-api.bitqiu.com

