#!name=百度网页去广告
#!desc=移除百度搜索移动端网页的首页广告信息流
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/Baidu.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Script]
移除百度搜索首页信息流广告 = type=http-response, pattern=^https?:\/\/(www|m)\.baidu\.com\/?($|\?from=\w{8,9}), script-path=https://kelee.one/Resource/JavaScript/BaiduSearch/BaiduSearchHomePage_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% m.baidu.com, www.baidu.com

