#!name=纷玩岛去广告
#!desc=移除开屏广告、弹窗广告、信息横幅推广、票夹页面横幅广告。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/LiveLab.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/api\.livelab\.com\.cn\/pgc\/advert\/ - reject-dict
^https:\/\/api\.livelab\.com\.cn\/search\/appHotWords\/app\/queryHotWords$ - reject-dict
^https:\/\/api\.livelab\.com\.cn\/appShow\/hotSearch\/app\/rankList$ - reject-dict
^https:\/\/api\.livelab\.com\.cn\/appShow\/app\/homepage\/banners\?bannerModuleId=(82|84|53) - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/api\.livelab\.com\.cn\/appShow\/app\/homepage\/modules\?tabId=5$ '.data |= map(select(.id | IN(51, 52, 81, 82, 83, 84)))'

[MITM]
hostname = %APPEND% api.livelab.com.cn

