#!name=网易有道词典去广告
#!desc=移除开屏广告、弹窗广告、右上角推广。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/YoudaoDict.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/dict\.youdao\.com\/vip\/activity\/startup\/ - reject-dict
^https:\/\/dict\.youdao\.com\/vip\/activity\/retention\/configs\? - reject-dict
^https:\/\/dict\.youdao\.com\/vip\/activity\/retention\/match\? - reject-dict
^https:\/\/dict\.youdao\.com\/vip\/user\/paid\/guide\? - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/dict\.youdao\.com\/homepage\/toolbar\/get\/ 'delpaths([["data","vipTag"]])'

[MITM]
hostname = %APPEND% dict.youdao.com

