#!name=胖乖生活去广告
#!desc=移除开屏广告、横幅轮播图、网格广告、信息流广告、浮窗广告，精简我的页面。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/PangguaiLife.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/userapi\.qiekj\.com\/slot\/get$ - reject-dict
^https:\/\/userapi\.qiekj\.com\/appTitle\/get$ - reject-dict
^https:\/\/userapi\.qiekj\.com\/integralRecord\/integralDailStatistics$ - reject-dict
^https:\/\/userapi\.qiekj\.com\/local-life\/category$ - reject-dict
^https:\/\/userapi\.qiekj\.com\/integralGoods\/queryIntegralGoodsPage$ - reject-dict
^https:\/\/userapi\.qiekj\.com\/task\/list$ - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/userapi\.qiekj\.com\/local-life\/tab-order$ 'if (getpath([]) | has("data")) then (setpath(["data"]; [])) else . end'
http-response-jq ^https:\/\/userapi\.qiekj\.com\/integralGoods\/queryIntegralGoodsCategoryList$ 'if (getpath([]) | has("data")) then (setpath(["data"]; [])) else . end'

[MITM]
hostname = %APPEND% userapi.qiekj.com

