#!name=自动加入TestFlight
#!desc=自动监控TestFlight名额，一旦有新的名额即刻加入。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/TestFlight.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Rule]
DOMAIN,testflight.apple.com,PROXY

[Script]
获取账号令牌 = type=http-request, pattern=^https?:\/\/testflight\.apple\.com\/v3\/accounts\/.*\/apps$, script-path=https://kelee.one/Resource/JavaScript/TestFlight/CaptureAccountToken.js

自动加入TF = type=cron, cronexp={{{TaskCron}}}, script-path=https://kelee.one/Resource/JavaScript/TestFlight/AutoJoinTF.js, timeout=600

监控TF位置 = type=cron, cronexp={{{TaskMonitor}}}, script-path=https://kelee.one/Resource/JavaScript/TestFlight/AutoMonitorTF.js, timeout=30

