#!name=萝卜快跑去广告
#!desc=移除开屏广告、弹窗广告、横幅广告、新用户活动皮肤，保留优惠活动。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/RoboTaxi.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/idgdata\.baidu\.com\/mc\/app\/api\/listterminal\? - reject-dict
^https:\/\/idgdata\.baidu\.com\/operation\/api\/announce\/screen\/image_manage\? - reject-dict
^https:\/\/idgdata\.baidu\.com\/idgactivity\/api\/newuser\/info\? - reject-dict

[MITM]
hostname = %APPEND% idgdata.baidu.com

