#!name=萤石云视频去广告
#!desc=移除开屏广告、首页推广、我的页面推广。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/VideoGo.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/api\.ys7\.com\/api\/ads - reject
^https:\/\/i\.ys7\.com\/api\/user\/tabList - reject-dict
^https:\/\/api\.ys7\.com\/v3\/config\/service\/entrance\/bannerInfo - reject-dict
^https:\/\/api\.ys7\.com\/v3\/intelligent-app\/apps\/linkage - reject-dict
^https:\/\/api\.ys7\.com\/v3\/configurations\/gray\/info\?grayTypes=185 - reject-dict
^https:\/\/api\.ys7\.com\/v3\/videoclips\/square\/video\/query - reject-dict

[MITM]
hostname = %APPEND% api.ys7.com, i.ys7.com

