#!name=行者户外去广告
#!desc=移除弹窗广告、发现页面横幅推广的推广金刚位，移除我的页面横幅推广。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/OnTheWay.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/www\.imxingzhe\.com\/api\/v1\/pop\/window\/\? - reject-dict

[Body Rewrite]
http-response-jq ^https:\/\/www\.imxingzhe\.com\/api\/v4\/account\/get_user_info\? 'delpaths([["banner"]])'
http-response-jq ^https:\/\/www\.imxingzhe\.com\/api\/v4\/discovery\/ios\/\? 'delpaths([["banners"]])'
http-response-jq ^https:\/\/www\.imxingzhe\.com\/api\/v4\/discovery\/ios\/\? 'delpaths([["ad"]])'
http-response-jq ^https:\/\/www\.imxingzhe\.com\/api\/v4\/discovery\/ios\/\? '.display_areas |= map(select(.name == "赛事" or .name == "行者帮" or .name == "头条" or .name == "排行榜" or .name == "约伴"))'

[MITM]
hostname = %APPEND% www.imxingzhe.com

