#!name=金山文档去广告
#!desc=移除首页横幅推广、表单收集页面推广和我的页面推广。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/WPS_Documents.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/www\.kdocs\.cn\/kdg\/api\/v1\/cards\/type\/3\?iosVer=\d+\.\d+\.\d+&isGetList=1 - reject-dict
^https:\/\/www\.kdocs\.cn\/kdg\/api\/v1\/cards\/type\/27\?iosVer=\d+\.\d+\.\d+&isGetList=1 - reject-dict
^https:\/\/f-api\.kdocs\.cn\/godfather\/api\/thirdparty\/v1\/viewpager\?showLocal=mobileWebIndex - reject-dict

[MITM]
hostname = %APPEND% www.kdocs.cn, f-api.kdocs.cn

