#!name=阿里云盘去广告
#!desc=移除首页广告横幅、弹窗和顶部奖励。
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/AliYunDrive.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[Rule]
IP-CIDR,203.107.1.1/24,REJECT,no-resolve

[URL Rewrite]
^https:\/\/member\.alipan\.com\/v2\/activity\/sign_in_luckyBottle - reject-dict
^https:\/\/api\.alipan\.com\/adrive\/v1\/file\/getTopFolders - reject-dict

[Script]
移除阿里云盘广告 = type=http-response, pattern=^https:\/\/(biz)?api\.alipan\.com\/apps\/v\d\/users?\/home\/(news|widgets), script-path=https://kelee.one/Resource/JavaScript/AliYunDrive/AliYunDrive_remove_ads.js, requires-body=true

移除阿里云盘广告 = type=http-response, pattern=^https:\/\/member\.alipan\.com\/v1\/users\/onboard_list, script-path=https://kelee.one/Resource/JavaScript/AliYunDrive/AliYunDrive_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% api.alipan.com, member.alipan.com, bizapi.alipan.com

