#!name=风鸟去广告
#!desc=移除首页信息流和轮播图
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/RiskBird.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
^https:\/\/m\.riskbird\.com\/prod-qbb-api\/user\/getBannerList - reject-dict
^https:\/\/m\.riskbird\.com\/prod-qbb-api\/searchHotEnt - reject-dict

[Script]
移除推荐老板 = type=http-response, pattern=^https:\/\/m\.riskbird\.com\/prod-qbb-api\/query\/person\/personRecommend, script-path=https://kelee.one/Resource/JavaScript/RiskBird/RiskBird_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% m.riskbird.com

