#!name=高德地图去广告
#!desc=高德地图去广告
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/gddt.png
#!homepage=https://github.com/dqzboy/Loon_Surge_Rule
#!author=dqzboy

[URL Rewrite]
# > 高德地图_Tip请求@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/boss\/order_web\/\w{8}_information - reject-200
# > 高德地图_通用广告请求@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/asa\/ads_attribution - reject
# > 高德地图_搜索框scene@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/shield\/scene\/recommend - reject-dict
# > 高德地图_首页左上角gif@ddgksf2013
^https?:\/\/.*\.amap\.com\/uploadimg\/\w+\.gif - reject-img
# > 高德地图_左下天气@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/valueadded\/weather - reject-dict

[Script]
# > 高德地图_首页底部处理@ddgksf2013
amap = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/faas\/amap-navigation\/main-page, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, requires-body=true, max-size=-1, timeout=60

# > 高德地图_开屏广告@ddgksf2013
amap = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/valueadded\/alimama\/splash_screen, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, requires-body=true, max-size=-1, timeout=60

# > 高德地图_首页顶部推广@ddgksf2013
amap = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/msgbox\/pull, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, requires-body=true, max-size=-1, timeout=60

# > 高德地图_我的页面@ddgksf2013
amap = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/shield\/dsp\/profile\/index\/nodefaas, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, requires-body=true, max-size=-1, timeout=60

# > 高德地图_搜索框热词@ddgksf2013
amap = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/shield\/search\/new_hotword, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, requires-body=true, max-size=-1, timeout=60

[MITM]
hostname = %APPEND% *amap.com

